version: '3.9'

services:
  pre-commit:
    build:
      context: .
      dockerfile: Dockerfile
    command: ${CMD:-bash}
    volumes:
      - .:/workdir
      - pre-commit-cache:/root/.cache/pre-commit
    working_dir: /workdir

volumes:
  pre-commit-cache:
